monitor.alsa.rules = [
  # Outputs
  {
    matches = [
      {
        node.name = "alsa_output.usb-Logitech_A50_X-00.pro-output-0"
      }
    ]
    actions = {
      update-props = {
        node.description = "A50 X Voice Output"
        node.nick = "A50 X Voice Output"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_output.usb-Logitech_A50_X-00.pro-output-1"
      }
    ]
    actions = {
      update-props = {
        node.description = "A50 X Game Output"
        node.nick = "A50 X Game Output"
      }
    }
  }

  # Inputs
  {
    matches = [
      {
        node.name = "alsa_input.usb-Logitech_A50_X-00.pro-input-0"
      }
    ]
    actions = {
      update-props = {
        node.description = "A50 X Headset Mic"
        node.nick = "A50 X Headset Mic"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_input.usb-Logitech_A50_X-00.pro-input-1"
      }
    ]
    actions = {
      update-props = {
        node.description = "A50 X Stream Mix Port"
        node.nick = "A50 X Stream Mix"
      }
    }
  }
]
